#+TITLE:vaarnan@'s blog
#+AUTHOR:Vaarnan Drolia
#+OPTIONS: num:nil
#+KEYWORDS: vaarnan,drolia,simplicity,pseudorandomness,technology
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="site.css" /> <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-42744207-1"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-42744207-1'); </script> <script src="func.js"></script><script>window.onload = linkifyTableOfContents</script> <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"><!-- HTML Meta Tags --><title>vaarnan@'s blog</title><meta name="description" content="Simplicity, Pseudorandomness and Technology"><!-- Facebook Meta Tags --><meta property="og:url" content="https://blog.vaarnan.com"><meta property="og:type" content="blog"><meta property="og:title" content="vaarnan@'s blog"><meta property="og:description" content="Simplicity, Pseudorandomness and Technology"><meta property="og:image" content="https://blog.vaarnan.com/profile.png"><!-- Twitter Meta Tags --><meta name="twitter:card" content="summary_large_image"><meta property="twitter:domain" content="blog.vaarnan.com"><meta property="twitter:url" content="https://blog.vaarnan.com/"><meta name="twitter:title" content="vaarnan@'s blog"><meta name="twitter:description" content="Simplicity, Pseudorandomness and Technology"><meta name="twitter:image" content="https://blog.vaarnan.com/profile.png">

* [2021-02-26 Fri] Dive or die
:PROPERTIES:
:CUSTOM_ID: dive-or-die-1
:END:

** The seed

*Water is fear, fear is water.*

I am in the university swimming pool with my friend.

 My breathing heavy, I cannot speak. *We are in waist-deep water*. Death feels close, an easy escape. *I am supposed to swim to the end*. I am hyper-ventilating. *My friend reassures me*. My most vulnerable, my most weak.

"We are a couple that goes on diving vacations, so you need to be certified", the unwavering relationship law dictated in a vacation "planning" session.

S describes diving as a surreal activity where you enter an entirely different world; a world where perception is completely altered. You are not in space, but you could be. You are not flying, but you could be. You are not high, but you could be. The first time you come out of the water, there is a subtle shift in the way you think about life, you have experienced something truly beautiful.

S is the Mark Antony of Antonys', a master orator. Rapture and enamor her audience she will. Lead them on and then pull back, ignite them with a thirst that begs for more. I am but a weak fearful mortal.

Hell-yeah I am hooked to give this diving thing a try. I dig up requirements for a certification because S assures me that she is not a great swimmer anyway, so you don't need to swim to dive.

That's when the most dreaded dive requirement that would haunt me for over a year, hits me - "be able to float on the water without aids for 10 minutes".

I look at that and know immediately that it is *impossible* for me to do.

Of course, we go back and forth for weeks and finally settle on going to the Maldives. Suddenly, we have a hotel with a 5-star PADI resort booked, this is the trip for my Open Water certification course. S executes, everything else flows.

And so begins swimming coaching and getting as much water time as possible. My crippling anxiety reassured by S, she makes me look forward to the trip. I have not felt anxiety like this, facing lifelong fears is not my everyday.

Dive or die?

/Comments on [[https://twitter.com/vaarnan][Twitter]]/

* [2021-02-22 Thu] 3 Rules to keep the Sensible Snark alive in any relationship
:PROPERTIES:
:CUSTOM_ID: 3-rules-to-keep-the-sensible-snark-alive-in-any-relationship
:END:

You may call it banter, witty wine exchanges or just good ole' snark. The hallmark of secure relationships with both (all?) partners and friends alike, is the ability to absolutely insult the very fabric of the other's existence.

Here are my three rules to keep the venomous verbiage at bay, persevere to preserve riposte revelry (new word!).

1. Never comment on something the other person is insecure or being vulnerable about. It's mean, just don't.

2. Sensible snark is not the way to communicate feedback or any other veiled criticism. Conversation is.

3. Be quick to apologize. 90% of your jokes are bad; *funny in head \supset funny when said*.

Have opinions? Maybe I'm interested, prolly not. Hit me up on [[https://twitter.com/vaarnan][twitter]]



* [2020-07-09 Thu] Eulogy for my aunt
:PROPERTIES:
:CUSTOM_ID: eulogy-for-my-aunt
:END:

The phone rings on queue. It's the late afternoon, post-lunch call. The bustle of the household settling now, a spare moment to relax and kick your feet back.

I run over to turn on the television and move it to the Sanskaar channel - I know the phone call is from my aunt. I know this because she calls regularly to check-in on how we are doing. I know this because she watches Aastha, and Sanskaar and anything that's alternative medicine smacked on yoga smacked on home remedies. My aunt watches this because my aunt is not just my aunt. She is my godmother, grandmother and my Dad's only sister, all wrapped in one endearing package.

My mum lifts the phone and hurries over to the telly giving me a soft smile for anticipating. Today's discussion is a television healer fresh with recommendations that one should devour cloves of garlic everyday to boost immunity. I know this is common knowledge in the new-age super-food era of California medicine where a chia-garlic-kale smoothie is the only way to go. Our late-90s healer is unfortunately too early to worship in California. He gets his fame in the afternoon slot typically set for a hundred million Indian mums so he can't really complain.

My aunt passed away today. I don't know how to articulate how I feel. No one knows really. I got off from a round-robin set of calls between my mum, my siblings, and my distraught and silent father. They were short. Declarative. Not many words exchanged. So much said in those silent sobs and sad-hushed voices.

I think my aunt lived a wonderful life. Never have I heard a mean word said, not a judgemental thought uttered about someone else. Growing up - love, patience and acceptance were all I saw from her. She was adorable in the way that she would softly repeat and insist you do something until your will-power ran down. You didn't really get angry because that feeling would be so misplaced up against her soft, warm demeanour. You just relented, and at the very least, listened.

Of course, she is an Indian aunt and would have loved to see me get married (the one thing we need to do (then have kids of course)). I didn't think much about it - obviously she would be there. I assumed in my static, fixed child world-view that she has been with our family through every up and down we have seen. Every happy moment swiftly reported to her because it made her happy or every sad moment swiftly reported to her because we knew she cared. My eventual wedding just another thing that we do together.

My aunt passed away today. I know now, I won't get to see her when I head back home. I know she won't be at my wedding. I know that she won't impact my life anymore. Anymore than she already has.

Miss you बुआजी

* [2020-08-30 Sun] Lockdown Ruminations
:PROPERTIES:
:CUSTOM_ID: lockdown-ruminations
:END:

2020 quietly dwindles away.

It started in the recesses of dark London flats punctuated by lonely lockdown chats. Life slowly trickles back to "normal", our memory of normalcy but a faint recollection.

'Nuff drama and talking about the times we live in (unpre...)

An exquisite dinner party with exquisite company led me to a conversation of gratitude for things done and a storage bog for the things not (yet) done.

Here they are as I recall them.


** things I did well

+ connected with my inner ⭕️ *in London*
  + in no particular order - Sid, Ellie, Sheraz, Adi, Devon, Jade, Gayatri
+ running, so much running
+ yoga
+ times I worked out 7min, push ups, HIIT
+ meditation everyday for 4 months
+ talked more to parents
+ read a lot (not read this much since school)
+ gained a stone, highest weight I've ever had in my life (mostly 💪 I believe)
+ submitted an incubator application
+ built [[https://vellvisher.github.io/TSExamples/][TSExamples]] and started learning TypeScript
+ built an app of my own outside of work (not done in several years)
+ learned to cook (more)
+ made some 💵 in the market, got better at options trading
+ made this bog

** things I failed (so far 🤷‍️)

+   online courses
+   startup incubator application
+   consistently working on my personal app
+   aerial silk conditioning
+   dance
+   workout consistently
+   weight training
+   keep up with Spanish
+   practice German
+   continue with TypeScript
+   learn to play the piano better
+   talk to Bhaiya/Bhabhi enough
+   finish the 🏠 deal
+   binge less TV/Netflix/streaming (whatever we call moving pictures)
+   taxes

* [2012-09-04 Tue] Adapting Innovation - E-Commerce Reloaded
:PROPERTIES:
:CUSTOM_ID: adapting-innovation-e-commerce-reloaded
:END:

I have had my own e-commerce start-up which practically blew up so I could relate to this session quite well.

Thus, I wanted to list the salient points of today's talk from the different speakers.

** Richard Tan - [[http://lelong.com.my][lelong.com.my]]

+ Serial e-commerce entrepreneur
+ Tech forum to sell things which started getting too many posts of non-tech goods
+ Instead of repeatedly deleting non-tech posts, spun off Lelong
+ Post paid payments did not work so offered a prepaid account
+ Buyers don't generally read, default top-up of RM38 instead of the minimum RM20 lead to a higher average
+ Buyers wanted to migrate from bidding to direct buying so added the feature
+ Could control the quality of the product so created a new website with curated store, Superbuy
+ Linked Superbuy to Lelong


** Daniel Tumiwa - [[http://multiply.com][multiply.com]]


+ Radio jockey to raise money for college
+ Great twitter fan following in Indonesia
+ 180,000+ people have him in their G+ circle
+ Indonesia's energy is chaos unlike the power of structure and process in Singapore
+ Click and pray model - whether the online item will be delivered to you
+ Multiply was based out of SV but shifted to Indonesia
+ Social media changing to E-Commerce since bloggers needed to be moved to the new platform
+ Channelled excessive demand by featuring popular bloggers so they are forced to switch to an organized e-commerce solution like Multiply's
+ Death threats for removing blogging option :D
+ Purpose/Passion for the team - Quest for a Better Life: The Indonesian Dream
+ Instant gratification for the team since sellers tell them about their experience with selling items on Multiply and supporting families
+ Don't care about Credit Cards (low penetration) but connect to banks via Internet Banking
+ ATM has an e-commerce option to pay directly to Multiply
+ Google influences e-commerce heavily
+ Localization not required since a lot of Malay people interacting with the Internet understand English
+ For scaling to the masses you need Bahasa.
+ E-commerce does not agree with the global model of the Internet
+ Amazon cannot maintain the level of service/standards everywhere so wouldn't fit well if it acquired Multiply

** Lai Kok Fung - [[http://buzzcity.com][buzzcity.com]]

+ Experienced the Dotcom crash
+ Naspers invested in BuzzCity
+ People consume media from Internet/mobile more but ad-spending on them disproportional
+ $20B Opportunity to expand to mobile
+ Three ways to advertise on mobile - Messaging, Banners, Search

Stealing some points from all the speakers, I analysed the failure of our startup and found that we were "blinded by the light" by trying to do too many things that interested us and did not try to do less, simplify and focus on satisfying one need. The approach taken by Richard in this respect was quite impressive as he iteratively built and catered to his users needs. Also, we were inexperienced, didn't know much of the industry and the dedication and passion for the idea was just not in the team as a whole.



But, nonetheless, one has to -

Keep fighting, innovating, adapting...
